---
title: "For Project"
author: "Kristy Phipps - 85842052"
date: "15/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(httr)
library(tidyverse)
library(ggplot2)
```



```{r}
#' @export
get_active_stores <- function() {
  #' @title Active store IDs and Store names
  #' 
  #' @description This function fetches all the active store IDs 
  #' and the store names in the API

  #' @return A dataframe with currently active stores and the store IDs being monitored by the API
 

  #' @examples
  #' get_active_stores()
  
  
    stores <- GET("https://www.cheapshark.com/api/1.0/stores")
   
        if (status_code(stores) != 200) {
            stop(paste("There was an error with the API. The reponse status is:", status_code(g)))
            }
     
    s <- content(stores, "parsed")       
    
    df <- s %>% 
          bind_rows %>% 
          filter(isActive == 1) %>%
          select(storeName, storeID) %>%
          distinct() %>%
          mutate(storeID = as.numeric(storeID))
    
    df
    
}

```


```{r}
#' @export
get_game_deals_df <- function(storeID, price_limit) {
  
  #' @title Get details about a store's game deals
  #' 
  #' @description This function fetches all the details about a
  #' store's on going deals on games with the mentioned price limit
  
  #' @param storeID integer. The store ID mentioned by the user
  #' @param price_limit integer. The budget entered by the user
  
  #' @return A dataframe containing a store's title, ID, 
  #' the actual price of the game, the sale price of the game, 
  #' the percentage of savings on purchase and the rating of the deal.
 

  #' @examples
  #' get_active_stores(1,800) 
  
    url <- paste0("https://www.cheapshark.com/api/1.0/deals?storeID=", storeID, "&upperPrice=", price_limit)
    
    g <- GET(url)
        if (status_code(g) != 200) {
            stop(paste("There was an error with the API. The reponse status is:", status_code(g)))
            }
            
    deals <- content(g, "parsed")
    
    df <- deals %>% 
            bind_rows%>%
            select(title, storeID, normalPrice, salePrice, savings, dealRating)%>%
            mutate(normalPrice = as.numeric(normalPrice), 
                   salePrice = as.numeric(salePrice), 
                   savings = as.numeric(savings), 
                   dealRating = as.numeric(dealRating), 
                   storeID = as.numeric(storeID))
    
    df
    
}

```

```{r}
#' @export
get_game_reviews_df <- function(storeID, rating) {
  #' @title Get details about a store's game reviews
  #' 
  #' @description This function fetches the rating for 
  #' all the games in a store
  
  #' @param storeID integer. The store ID mentioned by the user
  #' @param rating integer. The minimum rating mentioned by the user
  
  #' @return A dataframe containing the name of the game 
  #' and the meta critic score of the game.
  #'The meta critic score will be above the one mentioned by the user.
 

  #' @examples
  #' get_active_stores(31,80)
    url <- paste0("https://www.cheapshark.com/api/1.0/deals?storeID=", storeID, "&metacritic=", rating)
    
    g <- GET(url)
        if (status_code(g) != 200) {
            stop(paste("There was an error with the API. The reponse status is:", status_code(g)))
            }
            
    deals <- content(g, "parsed")
    
    df <- deals %>% 
            bind_rows%>%
            select(title, metacriticScore)%>%
            mutate(metacriticScore = as.numeric(metacriticScore))
    
    return(df)
    
}

```

```{r}
#' @export
get_deals_by_store_df <- function(storeID) {
  #' @title Get details about a store's maximum deals 
  #' 
  #' @description This function fetches the details 
  #' about the given store
  
  #' @param storeID integer. The store ID mentioned by the user
  
  #' @return A dataframe containing the name of the game,
  #' the store ID, the normal price of a game, the sale price on a game,
  #' the savings and the deal rating off the game.

  #' @examples
  #' get_active_stores(28)
    url <- paste0("https://www.cheapshark.com/api/1.0/deals?storeID=", storeID)
    
    g <- GET(url)
        if (status_code(g) != 200) {
            stop(paste("There was an error with the API. The reponse status is:", status_code(g)))
            }
            
    deals <- content(g, "parsed")
    
    df <- deals %>% 
            bind_rows%>%
            select(title, storeID, normalPrice, salePrice, savings, dealRating)%>%
            mutate(normalPrice = as.numeric(normalPrice), 
                   salePrice = as.numeric(salePrice), 
                   savings = as.numeric(savings), 
                   dealRating = as.numeric(dealRating))
    
    df
    
}
```



```{r}
response <- function(){
  #' @title Interactive function to pull interesting game price data
  #' 
  #' @description This function first pulls currently active store data. This active 
  #' store data is then given to the user to choose a store of interest. User then chooses a store from
  #' the active list. Next, user is presented with one one of three key options: budget, 
  #' deal rating and game rating. User choice on this section will dictate what data is returned from the API. 
  #' Data is first returned in a data frame, and is used to create a visualization based on user choice. 
  #' 
  #' @return a plot based on user input
  #' 
  #' @examples
  #' response()
 
y <- get_active_stores()  
    
cat("Please select a Store Number from below options \n")
 
  for (i in 1:nrow(y))
    {
    cat(y$storeName[i],":", y$storeID[i],"\n")
    }
  
  val <- readline("Enter value here: ")
  val <- as.integer(val)
  cat("Select what you want from the below options:\n 1. Game within a budget\n2.Savings and current deal rating\n3.Games above a certain rating")
  opt <- readline("Enter your choice : ")
  opt <- as.integer(opt)
  
  if(opt==1){
      bud <- readline("Enter your budget: ")
      bud <- as.integer(bud)
      data <- get_game_deals_df(val,bud)
      options(repr.plot.width=10, repr.plot.height=5)
      data %>% mutate(price_diff = normalPrice-salePrice) %>% arrange(desc(price_diff)) %>% head(10) %>%
      ggplot() +
      aes(
        x = salePrice,
        y = reorder(title,salePrice),
        color = title,
        fill = title,
      ) +
      geom_col() +
      labs(x="Game Sale Price",
           y='Game Titles',
           title='Top 10 Games Under Personal Budget')+
      theme_bw() +
      theme(legend.position="none") +
      scale_x_continuous(labels=scales::dollar_format()) +
      theme(axis.text.x = element_text(angle = 60,hjust=1,face='bold',size=10),
            axis.text.y = element_text(face='bold',size=10),
            axis.title = element_text(face='bold',size=12),
            plot.title = element_text(face='bold',size=12))
      
  }
  else if(opt==2){
      cat("Displaying top 10 games with high savings and their corresponding rating")
      deal <- get_deals_by_store_df(val)
      options(repr.plot.width=10, repr.plot.height=25)
      deal %>% arrange(desc(dealRating)) %>% head(10) %>%
      ggplot()+
      aes(
        x=title,
        y=savings,
        color=dealRating
      )+
      geom_point()+
      labs(x="Game",y='Rating',title='Top 10 games with high savings')+
      theme_bw()+
      theme(axis.text.x = element_text(angle = 60,hjust=1,face='bold',size=10),
            axis.text.y = element_text(face='bold',size=10),
            axis.title = element_text(face='bold',size=15),
            plot.title = element_text(face='bold',size=20))
  }
  else if(opt==3){
      rat <- readline("Enter the maximum percentage of rating required: ")
      rat <- as.integer(rat)
      ratings <- get_game_reviews_df(val,rat)
      options(repr.plot.width=10, repr.plot.height=25)
      ratings %>% arrange(desc(metacriticScore)) %>% head(10) %>%
      ggplot() + aes(x=title,y=metacriticScore) + geom_bar(stat="identity") + 
        ggtitle("Top 10 stores having expected reviews") +
        xlab("Company names") + ylab("Ratings") + theme_bw()+
        theme(axis.text.x = element_text(angle = 60,hjust=1,face='bold',size=10),
            axis.text.y = element_text(face='bold',size=10),
            axis.title = element_text(face='bold',size=15),
            plot.title = element_text(face='bold',size=20))
      
  }
  else {
      cat("You did not enter a valid input\n")
      break
  }
}



```

```{r}
response()
```















